### ISSUE TITLE
ssoDemo: Error from web service: unauthorized_client

### ISSUE THREAD

**Issue by KaushalKhamar** [OfficeDev/msteams-tabs-sso-sample-nodejs#1]
I have configured this code to run in MS Teams but after getting client-side token I am getting an error while getting server-side token as below.

ssoDemo: Error from web service: unauthorized_client

Any idea of this?

**Comment by krishan1kamal** [comment]
@KaushalKhamar how did you resolve this?

**Comment by KaushalKhamar** [comment]
@krishan1kamal  You need to provide consent to get tokens.
